### POST Register and sends email with verification code
POST http://localhost:8080/auth/register
Content-Type: application/json

{
   "username": "tomdion35@gmail.com",
    "password":"password123"
}

### POST Request that sumbits verification code given

POST http://localhost:8080/auth/verify
Content-Type: application/json

{
  "email": "argel6767@gmail.com",
  "verificationToken": "9939359"
}

### Post Request that will be 200 and return JWT Token and time till expiration

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "argel6767@gmail.com",
  "password": "password123"
}


### POST Request for resend that should send a 400, because email is already verified

POST http://localhost:8080/auth/resend
Content-Type: application/json

{
  "email": "argel6767@gmail.com"
}

###

### POST Request for resend that should send a 200 and send email, because email is not verified

POST http://localhost:8080/auth/resend
Content-Type: application/json

{
  "email": "tomdion35@gmail.com"
}

###