### PUT request for add users profession
PUT http://localhost:8080/user/profession
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email":"argel6767@gmail.com",
  "profession":"Software Engineer"
}
###

### GET request for getProfessionStatus
GET localhost:8080/user/profession/status
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "tailor.ai.com@gmail.com"
}
###