### PUT request for add users profession
PUT {{endpoint}}/user/profession
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email":"tailor.ai.com@gmail.com",
  "profession":"Software Engineer"
}
###

### GET request for getProfessionStatus
GET {{endpoint}}/user/profession/tailor.ai.com@gmail.com
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###